= nxt-auto-forge
Chevdor
v0.1.0

image:https://travis-ci.org/chevdor/nxt-auto-forge.svg["Build Status", link="https://travis-ci.org/chevdor/nxt-auto-forge"]

image::https://badge.waffle.io/chevdor/nxt-auto-forge.svg?label=ready&title=ready[link="http://waffle.io/chevdor/nxt-auto-forge"] 
image::https://badge.waffle.io/chevdor/nxt-auto-forge.svg?label=inprogress&title=inprogress[link="http://waffle.io/chevdor/nxt-auto-forge"] 
image::https://badge.waffle.io/chevdor/nxt-auto-forge.svg?label=done&title=done[link="http://waffle.io/chevdor/nxt-auto-forge"]

== What is nxt-auto-forge?

This command line utility written in NodeJS checks whether your Nxt node is forging or not and if not, if will start forging and notify you. Read more about the Nxt network at http://nxt.org/

== Requirements

Before you can use this package, you will need a running Nxt client and NodeJS.

== Install
You can install this package using npm:

	npm install -g nxt-auto-forge

See details here: https://www.npmjs.com/package/nxt-auto-forge

== Getting started

The best to get started is to copy the sample config file. First go to the install folder. It should be still displayed on screen if you just installed. It will be something like +/opt/node/lib/node_modules/nxt-auto-forge+

	cp config-sample.js config.js

Then use your favorite text editor to edit at least the target section of the config.js file.

== Run
Execute the following command:

	nxt-auto-forge

Check the available flags using:

	nxt-auto-forge.js --help

Use the -s flags for some stats about your address.

== Support

Your support is more than appreciated. You can send a few Nxt over here: 

	NXT-YCLA-V44V-USJK-3GPJD