= nxt-auto-forge
Chevdor
v1.0.0

image:https://travis-ci.org/chevdor/nxt-auto-forge.svg["Build Status", link="https://travis-ci.org/chevdor/nxt-auto-forge"]

image::https://badge.waffle.io/chevdor/nxt-auto-forge.svg?label=ready&title=ready[link="http://waffle.io/chevdor/nxt-auto-forge"] 
image::https://badge.waffle.io/chevdor/nxt-auto-forge.svg?label=inprogress&title=inprogress[link="http://waffle.io/chevdor/nxt-auto-forge"] 
image::https://badge.waffle.io/chevdor/nxt-auto-forge.svg?label=done&title=done[link="http://waffle.io/chevdor/nxt-auto-forge"]

== What is nxt-auto-forge?

This command line utility written in NodeJS checks whether your Nxt node is forging or not and if not, if will start forging and notify you. Read more about the Nxt network at http://nxt.org/

== Requirements

Before you can use this package, you will need a running Nxt client and NodeJS.

== Install
You can install this package using npm:

	npm install -g nxt-auto-forge

See details here: https://www.npmjs.com/package/nxt-auto-forge
On a Rpi, you may need to symlink node:

	sudo ln -s /opt/node/bin/node /usr/local/bin/node

== Getting started

The best to get started is to copy the sample config file. First go to the install folder. It should be still displayed on screen if you just installed. It will be something like +/opt/node/lib/node_modules/nxt-auto-forge+

	cp config-sample.js config.js

Then use your favorite text editor to edit at least the target section of the config.js file.

== Run
=== Manually
First check what version you have:

	nxt-auto-forge -v

Execute the following command:

	nxt-auto-forge

Check the available flags using:

	nxt-auto-forge.js --help

Use the -s flags for some stats about your address.

=== Using crontab
Obviously, you don´t want to be seating around. You can run nxt-auto-forge on schedule using crontab:
	crontab -e

Then add the following line:

	*/15 * * * * /usr/local/bin/nxt-auto-forge	

This example will run nxt-auto-forge every 5 minutes 24/7, 7 days a week to ensure you keep forging.

== Support

Your support is more than appreciated. You can send a few Nxt over here: 

	NXT-YCLA-V44V-USJK-3GPJD